### ISSUE TITLE
Ask for scripts to generate coco_caption dataset in Oscar format

### ISSUE THREAD

**Issue by ZuoJiaxing** [microsoft/Oscar#10]
Could you please also release the scripts to generate the coco_caption dataset used here? https://biglmdiag.blob.core.windows.net/oscar/datasets/coco_caption.zip

Although I know that you leverage the bottom-up-attention to generate the boxes, features and so on, it's hard for me to generate the data of the same format as you provide:
label: *.label.tsv
feature: *.feature.tsv
caption: *.json

**Comment by ZuoJiaxing** [comment]
Or could you tell me the exact format of the *.feature.tsv file? What kind of method did you use to encode the feature?

**Comment by xiyinmsu** [comment]
Hi, you can refer to the following code to generate the feature files. We use bottom-up-attention to generate the boxes and features. And then concatenate the features with box spatial location. 

`# compute scaled spatial features
            box_width = boxes[:, 2] - boxes[:, 0]
            box_height = boxes[:, 3] - boxes[:, 1]
            scaled_width = box_width / image_width
            scaled_height = box_height / image_height
            scaled_x = boxes[:, 0] / image_width
            scaled_y = boxes[:, 1] / image_height
            scaled_width = scaled_width[..., np.newaxis]
            scaled_height = scaled_height[..., np.newaxis]
            scaled_x = scaled_x[..., np.newaxis]
            scaled_y = scaled_y[..., np.newaxis]
            spatial_features = np.concatenate(
                 (scaled_x,
                  scaled_y,
                  scaled_x + scaled_width,
                  scaled_y + scaled_height,
                  scaled_width,
                  scaled_height),
                 axis=1)
            full_features = np.concatenate((features, spatial_features), axis=1)
            fea_base64 = base64.b64encode(full_features).decode('utf-8')
            fea_info = {'num_boxes': boxes.shape[0], 'feature': fea_base64}
            row = [[image_key, json.dumps(fea_info)]
`
