### ISSUE TITLE
Pretrained Model Release

### ISSUE THREAD

**Issue by xiaoleihuang** [microsoft/Oscar#12]
Hi,

In table 1, the paper claims to use the assembled dataset to pretrained model weights, but in the released pretrained models, both base and large models are from either visual genome or open image. Do you release the pretrained models on the assembled dataset?

**Comment by xjli** [comment]
Text-image pairs are from the *assembled dataset*.
Image tags are from visual genome or open image category. 

Please read the paper carefully...

**Comment by VickiCui** [comment]
I'm still confused. Which model does the OSCAR_base model in the paper refer to? base-vg-labels or base-oid-labels?

**Comment by VickiCui** [comment]
I'm still confused. Which model does the OSCAR_base model in the paper refer to? base-vg-labels or base-oid-labels?
