### ISSUE TITLE
Cannot find eval caption index file when testing image/text retrieval ..

### ISSUE THREAD

**Issue by byougert** [microsoft/Oscar#124]
First of all, many thanks for your sharing VinVL model.
However, when I used [Flickr-30k](https://github.com/microsoft/Oscar/blob/master/VinVL_DOWNLOAD.md#pre-exacted-image-features) pre-extracted features to finetune for Oscarplus base to evaluate [Image/Text Retrieval](https://github.com/microsoft/Oscar/blob/master/VinVL_MODEL_ZOO.md#image-text-retrieval), I found I missed --eval_caption_index_file minival_caption_indexs_top20.pt. So would you mind sharing the download link?  Where could i get the minival_caption_indexs_top20.pt?
Thanks!

**Comment by RulinShao** [comment]
> Hi, I meet the same issue. Did you finally solve that?

Same here, any idea?

**Comment by RulinShao** [comment]
> > Hi, I meet the same issue. Did you finally solve that?
> 
> Same here, any idea?

Download through:
`azcopy copy 'https://biglmdiag.blob.core.windows.net/vinvl/datasets/coco_ir' ./ --recursive`
