### ISSUE TITLE
How to use Pre-exacted Image Features?

### ISSUE THREAD

**Issue by byougert** [microsoft/Oscar#125]
Taking Flickr30k as example, is it correct to copy [Pre-exacted Image Features](https://github.com/microsoft/Oscar/blob/master/VinVL_DOWNLOAD.md#pre-exacted-image-features) folder (including 5 files: features.lineidx  features.tsv  imageid2idx.json  predictions.lineidx  predictions.tsv) to dataset/coco_ir downloaded from https://github.com/microsoft/Oscar/blob/master/VinVL_DOWNLOAD.md#datasets ?

**Comment by Bovey0809** [comment]
Is it the write way to use the features?
