### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by txbb-lx** [microsoft/Oscar#154]
I encoutered the assertionerror when executing the run_retrieval for the text-image retrieval task
python oscar/run_retrieval.py \
    --model_name_or_path pre-train/checkpoint-0132780 \
    --do_test \
    --do_lower_case \
    --evaluate_during_training \
    --num_captions_per_img_val 20 \
    --eval_caption_index_file minival_caption_indexs_top20.pt \
    --per_gpu_train_batch_size 16 \
    --learning_rate 0.00002 \
    --num_train_epochs 30 \
    --weight_decay 0.05 \
    --save_steps 5000 \
    --add_od_labels \
    --od_label_type vg \
    --max_seq_length 70 \
    --max_img_seq_length 70 \
    --output_dir  checkpoint-0132780/

File "oscar/run_retrieval.py", line 668, in <module>
    main()
  File "oscar/run_retrieval.py", line 620, in main
    assert op.isdir(checkpoint)
AssertionError

Do anyone have some suggestions?

**Comment by via815via** [comment]
I encoutered the same problem, do you solve this? Thank you very much!

**Comment by txbb-lx** [comment]
> I encoutered the same problem, do you solve this? Thank you very much!

Maybe you didn't use the correct link to download the whole dataset. The correct link is named as "COCO 2014 Train/Val Image Features (~50G)".
