### ISSUE TITLE
The Num examples of COCO 1K and 5K test set

### ISSUE THREAD

**Issue by txbb-lx** [microsoft/Oscar#161]
When I was running, it shows that the number of examples in COCO 1K and 5K are 5000000 and 125000000 respectively. It should be 1000 and 5000 respectively. What's wrong with that? The feature is from the COCO Train/Val dataset downloaded from the given link. Could anyone give me some suggestions? Thanks a lot!

**Comment by IKACE** [comment]
I believe you have to turn off cross_image_eval flag.
