### ISSUE TITLE
How can i generate caption for any(my) image?

### ISSUE THREAD

**Issue by Kangjunseo** [microsoft/Oscar#19]
In coco_caption dataset,  train.yaml file shows that train.img.tsv is an image, but i couldn`t found train.img.tsv.
1. Where can i find the train(val or test).img.tsv?

feature: train.feature.tsv 
> 391895	{"num_boxes": 37, "features": "W6aDPlMKLj6FySc9zdycPyewQj7zsqw/8FjLQE+ABUEspTk+AAAAAEg0Dz8FzHo

2. Can you explain how you changed original image to feature?

What I want to do is look at the image, caption example, like in your paper Fig5.
3. how can i generate caption for any sample image? 
![image](https://user-images.githubusercontent.com/33209250/86891607-130b6800-c13a-11ea-97e7-705915f40c73.png)

**Comment by xiyinmsu** [comment]
Currently we only support to inference with image features. You can use the bottom-up top-down approach to extract features and labels first and then use our pipeline to generate the captions.

**Comment by amil-rp-work** [comment]
Hey @xiyinmsu 
Could the following repo work for feature extraction [https://github.com/airsplay/py-bottom-up-attention](https://github.com/airsplay/py-bottom-up-attention)?
