### ISSUE TITLE
Pretraining Process

### ISSUE THREAD

**Issue by Linkaiyi123** [microsoft/Oscar#2]
Thanks for your great work！
Could you please provide the codes of the pretraining process. 
What should i follow, if i wanna pre-train the model with other dataset?
Thanks again!

**Comment by xjli** [comment]
Thanks for your interest. 

For the pre-training pipeline, we plan to release it in the second phase soon. Stay tuned. Thanks much.

**Comment by Linkaiyi123** [comment]
Thanks！Looking forward to your work.
