### ISSUE TITLE
Coco caption pertained model output results are not good

### ISSUE THREAD

**Issue by joey-wang123** [microsoft/Oscar#21]
Hello,

        Thank you for your great works!

        I used your pertained model for coco image captioning. Here is the command I used.

       python oscar/run_captioning.py \
    --do_test \
    --do_eval \
    --test_yaml test.yaml \
    --per_gpu_eval_batch_size 64 \
    --num_beams 5 \
    --max_gen_length 20 \
    --eval_model_dir image_caption/Oscarrepo/Oscar/checkpoint-29-132780/

where checkpoint-29-132780 is uncompressed pertained coco model folder. But the outputs are not good.
Some following examples are the following:

caption     claire libraries libraries libraries libraries libraries robbery libraries libraries libraries libraries libraries libraries libraries librariesletsletslets
caption    demanded adoptedrredrred libraries libraries libraries libraries librariessteadsteadsteadsteadsteadstead libraries libraries libraries
caption    typing curvature curvature libraries curvature curvature curvature curvature curvature curvature curvature curvature curvature curvature curvature curvature curvature

Do I miss some important steps? Thank you for your help!
Also, where is the test.yaml. Thanks

**Comment by joey-wang123** [comment]
Also, where is the test.yaml. Thanks

**Comment by xiyinmsu** [comment]
test.yaml is from the dataset coco_caption folder. We have it in the DOWNLOAD page. 

How do you generate the caption if you do not have our dataset? If you use your extracted features and labels, the results might be undesirable because of the feature/label mismatch.

**Comment by joey-wang123** [comment]
Currently, I change the path to text.yaml. But the results are still the
same, I use the dataset downloaded from your github. Do I missed some
important steps? Thank you!

Xi Yin <notifications@github.com> 于2020年7月15日周三 上午12:49写道：

**Comment by xiyinmsu** [comment]
Hi, I just checked it again on my side and I am able to get good results. I think you probably have used the wrong checkpoint. For image captioning model, after you unzip it, the model path is "checkpoint-29-66420". 

In your command, you write "checkpoint-29-132780", looks liked you have used the model trained from a different task for image captioning task. So the results are random.

**Comment by joey-wang123** [comment]
Great, thank you!

Xi Yin <notifications@github.com> 于2020年7月15日周三 下午6:05写道：

**Comment by whqwill** [comment]
@xiyinmsu Hi, I meet the same problem, the result is like:

marcia marcia発発発発発発発発発発 haitian haitian haitian corruptionyo southend
traps factual mosque བ བ བ བyo pat hypotheticalyo trapsyo traps hyper चyo southend
corruption marian marian བ བ བ བ marian marian lionsyo parryyo parry hyper wilburyo原
mechanisms mechanisms mechanisms wilkes mechanisms declares declares declares declares declares declares declares declaresfrey horriblyyo patク
blond marcia marcia challenged marcia marcia marcia marcia marcia marcia marcia marciachus marcia vishnuyo patク
marcia marcia pietro ri parry pat noiseco faust develops พ พ พ melee melee melee marian daggers
faust faust発発 lax lax accountant hardly dripped lax traps – lax hyper hardly travelyo pat
rendezvous marcia pietro pietro ri parry patク ara pat hypotheticalfreyyo parry detail daggers epilogue epilogue


But I do use the "checkpoint-29-66420".

**Comment by DesaleF** [comment]
@xiyinmsu  I also use "checkpoint-29-66420" for my own images. I extracted the feature using [bottom-up-attention](https://github.com/airsplay/py-bottom-up-attention). But the result is somewhat weird. Is there anything I can do to get a better result. I also tested the same images with other models trained on coco and I got a decent captions but for Oscar the result looks like this:

konstantin konstantin konstantin konstantin konstantin ymca ymca ymca ymca ymca ymca konstantin konstantin konstantin konstantincha konstantin konstantin
ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymcaunds ymca ymca
complexion brad complexion complexion complexion complexion brad complexion complexion complexion complexion complexion complexion brad brad antenna antenna recently
bringing ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca ymca departmental ymca ymca
brad brad brad brad brad brad brad brad brad brad brad brad complexion brad brad\u10d1 brad brad
comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise\u10d1 comprise\u10d1
comprise comprise comprise comprise comprise planetary comprise comprise comprise comprise comprise comprise comprise comprise comprise winters comprise comprise 
comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise comprise compriselogists comprise comprise 

Is there anything that I can do to get a good caption(atleast a reasonable sentence)?

**Comment by liuheng92** [comment]
> got bad result when predicting #140

Have you solved it?

**Comment by liuheng92** [comment]
> 

Have you solved it?

**Comment by liuheng92** [comment]
> @xiyinmsu Hi, I meet the same problem, the result is like:
> 
> marcia marcia発発発発発発発発発発 haitian haitian haitian corruptionyo southend traps factual mosque བ བ བ བyo pat hypotheticalyo trapsyo traps hyper चyo southend corruption marian marian བ བ བ བ marian marian lionsyo parryyo parry hyper wilburyo原 mechanisms mechanisms mechanisms wilkes mechanisms declares declares declares declares declares declares declares declaresfrey horriblyyo patク blond marcia marcia challenged marcia marcia marcia marcia marcia marcia marcia marciachus marcia vishnuyo patク marcia marcia pietro ri parry pat noiseco faust develops พ พ พ melee melee melee marian daggers faust faust発発 lax lax accountant hardly dripped lax traps – lax hyper hardly travelyo pat rendezvous marcia pietro pietro ri parry patク ara pat hypotheticalfreyyo parry detail daggers epilogue epilogue
> 
> But I do use the "checkpoint-29-66420".

Have you solved it?
