### ISSUE TITLE
Can you release the features extraction code or explain how the extracted image region features organized?

### ISSUE THREAD

**Issue by soulmeetliang** [microsoft/Oscar#26]
Good work, Thanks!

**Comment by xjli** [comment]
I actually used the opensourced bottom-up attention repo for feature extraction, https://github.com/peteanderson80/bottom-up-attention

**Comment by soulmeetliang** [comment]
> I actually used the opensourced bottom-up attention repo for feature extraction, https://github.com/peteanderson80/bottom-up-attention

thanks！

**Comment by EByrdS** [comment]
> > I actually used the opensourced bottom-up attention repo for feature extraction, https://github.com/peteanderson80/bottom-up-attention
> 
> thanks！

Hello! I managed to clone peteanderson80's repo, and it works as expected, here is the generated caption for one COCO image:

![bottom_up_attention_coco_proof](https://user-images.githubusercontent.com/25442086/94717395-e10f3980-0315-11eb-8535-8fc0361407a2.png)

The question is, how do I get the "features" generated for that image?

I generated this labeled image using the notebook on *tools/demo.ipynb*: https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/demo.ipynb.

I tried the code on https://github.com/microsoft/Oscar/issues/10#issuecomment-641024636. But it seems like not all the variables that are used in that code are available at the end of the demo. For example, the variable `features`. If you managed to extract the features in the required format, can you explain a little bit further on how you did it? Thanks!
