### ISSUE TITLE
Question about t2i retrieval task

### ISSUE THREAD

**Issue by vincentlux** [microsoft/Oscar#28]
Hi, thank you very much for open source the project! I tried to reproduce the text-to-image retrieval task. However, it appears that only image-to-text retrieval code has been released. May I ask if it is possible to release the text-to-image retrieval code and model as well? Thank you very much for your help!

**Comment by xjli** [comment]
It is in the coco_ir data folder (coco_ir.zip), please set the --data_dir to the right data path (the path of coco_ir).
