### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by tjdevWorks** [microsoft/Oscar#29]
Failing to clone the repo and its submodules, please help.

```
$git clone --recursive git@github.com:microsoft/Oscar.git
Cloning into 'Oscar'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Additionally for cloning using https "https://github.com/microsoft/Oscar.git", the submodules fail to install giving the same error:
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by tjdevWorks** [comment]
Ok no problem found a workaround:

1. Clone the Oscar repo using: `git clone https://github.com/microsoft/Oscar.git`

2. Update the Git submodules with the below contents
```
[submodule "transformers"]
	path = transformers
	url = https://github.com/huggingface/transformers.git
	branch = 067923d3267325f525f4e46f357360c191ba562e
[submodule "coco_caption"]
	path = coco_caption
	url = https://github.com/LuoweiZhou/coco-caption.git
	branch = de6f385503ac9a4305a1dcdc39c02312f9fa13fc
```
3. Execute `git submodule update --init --recursive --progress` inside the oscar repo to load the submodules.

**Comment by xjli** [comment]
Thanks, I just checked, it worked at my side. 
Great to see you figured it out. Thanks.

![image](https://user-images.githubusercontent.com/7686573/92208920-fc834380-ee40-11ea-93ab-7c788e77d7b1.png)

**Comment by liutianling** [comment]
@tjdevWorks 
I don't know how to load the submodules.
Could you tell me the whole command of step 3 ? I run the command "git submodule update --init --recursive --progress" with the result of follows:

usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] [--] <path>...
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference <repository>] [--merge] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]

Thanks.

**Comment by liutianling** [comment]
@xjli Hi, I am also meet with the same error of install.
Could you give some other way of install?
Thanks!

**Comment by FingerRec** [comment]
@liutianling it means update .gitmodules under Oscar.  
<img width="766" alt="image" src="https://user-images.githubusercontent.com/20349006/127615007-26f59b08-876a-460a-bf71-b8b36cf43b1c.png">

**Comment by Linh0704** [comment]
> @tjdevWorks I don't know how to load the submodules. Could you tell me the whole command of step 3 ? I run the command "git submodule update --init --recursive --progress" with the result of follows:
> 
> usage: git submodule [--quiet] add [-b ] [-f|--force] [--name ] [--reference ] [--] [] or: git submodule [--quiet] status [--cached] [--recursive] [--] [...] or: git submodule [--quiet] init [--] [...] or: git submodule [--quiet] deinit [-f|--force] [--] ... or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--rebase] [--reference ] [--merge] [--recursive] [--] [...] or: git submodule [--quiet] summary [--cached|--files] [--summary-limit ] [commit] [--] [...] or: git submodule [--quiet] foreach [--recursive] or: git submodule [--quiet] sync [--recursive] [--] [...]
> 
> Thanks.

You should upgrade git version, --progress is supported in 2.13 version or newer

**Comment by mumulmaulana** [comment]
> Ok no problem found a workaround:
> 
> 1. Clone the Oscar repo using: `git clone https://github.com/microsoft/Oscar.git`
> 2. Update the Git submodules with the below contents
> 
> ```
> [submodule "transformers"]
> 	path = transformers
> 	url = https://github.com/huggingface/transformers.git
> 	branch = 067923d3267325f525f4e46f357360c191ba562e
> [submodule "coco_caption"]
> 	path = coco_caption
> 	url = https://github.com/LuoweiZhou/coco-caption.git
> 	branch = de6f385503ac9a4305a1dcdc39c02312f9fa13fc
> ```
> 
> 3. Execute `git submodule update --init --recursive --progress` inside the oscar repo to load the submodules.

Using this workaround and running `git submodule sync` before `git submodule update --init --recursive --progress` works for me
