### ISSUE TITLE
how to convert gqa_objects_x.h5 file to gqa_img_frcnn_feats.pt？

### ISSUE THREAD

**Issue by linxi1158** [microsoft/Oscar#3]

**Comment by xjli** [comment]
if you mean the "gqa_objects_x.h5" provided by GQA dataset, we are not using the objects provided by GQA dataset, the gqa_img_frcnn_feats.pt are using Faster R-CNN to exact object features on GQA images.

**Comment by linxi1158** [comment]
thanks
