### ISSUE TITLE
Few questions about the paper.

### ISSUE THREAD

**Issue by xden2331** [microsoft/Oscar#30]
Our group is currently reviewing your paper. It's awesome :D.

We have a few questions about the model.

1. Which Faster R-CNN version is used in OSCAR? Is the one on Ross Girshick’s GitHub? or your group reproduce it.
2. In Image Captioning, the paper says repeating the process until **[STOP]** token is detected. Is **[STOP]** token **[SEP]** in BERT?
3. During Image Captioning fine-tuning, the paper says “We randomly mask out 15% of the caption tokens…”. Are 15% of the caption tokens masked or each word has a 15% probability to be masked?

Looking forward to reviewing the source code. :D
Cheers

**Comment by xjli** [comment]
1. https://github.com/peteanderson80/bottom-up-attention
2. SEP
3. 15% of the caption tokens masked
