### ISSUE TITLE
Generating label.lineidx and feature.lineidx for my own images

### ISSUE THREAD

**Issue by shravan1394** [microsoft/Oscar#32]
Hey guys, Great work!! I am trying to run the model on my own images. I followed other issues and was able to generate my own feature.tsv and label.tsv files. But I am not sure on how to generate feature.lineidx and label.lineidx files for my own images. I am not sure if I am missing something. it would be great if you could help me with this issue.
 
Thanks

**Comment by xiyinmsu** [comment]
Hi you can use this function: https://github.com/microsoft/Oscar/blob/master/oscar/utils/tsv_file.py#L8

**Comment by sameerpande12** [comment]
Hi, I am trying to generate my own features as well, but I am confused with what exactly are the features. Are these derived from feature maps of some intermediate layers of faster-R-CNN or these are created from the outputs of faster-R-CNN? 

I am relatively new to the field, any help would be appreciated.

**Comment by sameerpande12** [comment]
Hi @shravan1394  and @xiyinmsu, I am also trying to create feature.tsv and label.tsv, but I am confused regarding the exact layer from where these 2048 dimensional vectors are extracted in the Faster-RCNN. 

I have gone through the paper but I still feel confused about it. Can you please help me ?
I am relatively new to this area, any help would be appreciated.

**Comment by xiyinmsu** [comment]
Hi, it is the feature representation before the last FC classifier. 


> Hi @shravan1394 and @xiyinmsu, I am also trying to create feature.tsv and label.tsv, but I am confused regarding the exact layer from where these 2048 dimensional vectors are extracted in the Faster-RCNN.
> 
> I have gone through the paper but I still feel confused about it. Can you please help me ?
> I am relatively new to this area, any help would be appreciated.
