### ISSUE TITLE
ERROR 404: The specified blob does not exist

### ISSUE THREAD

**Issue by wanghao411** [microsoft/Oscar#34]
When I run the command: wget https://biglmdiag.blob.core.windows.net/oscar/datasets/$coco_ir.zip. The following error has occurred:
--2020-10-01 19:55:19--  https://biglmdiag.blob.core.windows.net/oscar/datasets/.zip
Resolving biglmdiag.blob.core.windows.net (biglmdiag.blob.core.windows.net)... 52.239.247.100
Connecting to biglmdiag.blob.core.windows.net (biglmdiag.blob.core.windows.net)|52.239.247.100|:443... connected.
HTTP request sent, awaiting response... 404 The specified blob does not exist.
2020-10-01 19:55:20 ERROR 404: The specified blob does not exist..
How can I solve it?

**Comment by xjli** [comment]
wget https://biglmdiag.blob.core.windows.net/oscar/datasets/coco_ir.zip
