### ISSUE TITLE
Extracted feature for VQA test-dev set

### ISSUE THREAD

**Issue by weiyx16** [microsoft/Oscar#38]
Thank you for making this excellent work public!
I hope to reproduce your result on vqa task, but some problem occurred about the dataset.
I downloaded the vqa dataset following this instruction: https://github.com/microsoft/Oscar/blob/master/DOWNLOAD.md#datasets, and I didn't find image frcnn feature for test-dev. I'm not sure if there's some mistake during my downloading, or this part just wasn't provided.
If it's not possible to share frcnn features for test-dev, could you please provide some code and basic information about how to extract the features myself, so I can reproduce the work correctly. For example,
+ the features were extracted by which version of faster rcnn?
+ what's the correct structure to save these features? [i.e. for each image, how to organize all rois features&location and bound them with image id or question id]

Really thank you for your kind help!

**Comment by clytze0216** [comment]
Hello?
Do you find the image frcnn feature for test-dev?I also want to reproduce the result on vqa task

**Comment by weiyx16** [comment]
Nope. I extracted the frcnn feature myself. Mostly, you can ref to this useful (issue)[https://github.com/microsoft/Oscar/issues/33] which will help you extract the test-dev features.

**Comment by clytze0216** [comment]
@weiyx16
Thanks a lot !
sorry for bothering you again.I have tried it for a long time ,but I do not succeed .I am relatively new to this area. 
So Could you please share the test-dev feature with me? I'm really sorry if this is inconvenient for you.
Looking forward to your reply. Thank you very much!

**Comment by weiyx16** [comment]
No problem. The file is a little big and I will share it through the google drive later. Please tell me your google account through email (mine is wei-yx20@mails.tsinghua.edu.cn). Besides, as far as I remember, the generated question-answer indexes have some small mistakes (maybe an error will occur when directly submit to the test-dev benchmark), you may need some more effort to correct it. If found anything unsolved, feel free to contact me.
