### ISSUE TITLE
release the fine-tuned model for Image Text Retrieval ?

### ISSUE THREAD

**Issue by dixonhsiao** [microsoft/Oscar#4]
may I ask : how much time does it take to do finetuning for the Image Text Retrieval task ? and is it possible to release the fine-tuned model so we can directly inference on the coco dataset ? because the training with (4 V100 with 16G mem) or (8 V100 with 32G mem) is kinda expensive...

**Comment by xjli** [comment]
Generally, base model takes 30+ hours for finetuning on 4*V100 (32GB), and large model takes more than twice of that time. 

Great suggestion.
We will release some finetuned checkpoints very soon, stay tuned.

**Comment by xiyinmsu** [comment]
@dixonhsiao The retrieval model is released. Please check MODEL_ZOO.md
