### ISSUE TITLE
image feature has a different size rather than 2054

### ISSUE THREAD

**Issue by Xuefei98** [microsoft/Oscar#50]
The dataset I am using has image feature size of 2048. But bert.img_embedding.weight has a size of [768, 2054]. What am I suppose to do? padding all 0 after each image feature? Thanks!

**Comment by xjli** [comment]
See the last paragraph on Page 4, it also contains 6d spatial vectors (see footnote 3 on page 5).

**Comment by Xuefei98** [comment]
That's really helpful! Thank you so much!
