### ISSUE TITLE
 multi-gpu training returns Error

### ISSUE THREAD

**Issue by Xuefei98** [microsoft/Oscar#52]
apex was installed successfully but it returns error when I ran gqa and vqa examples.
![Screenshot from 2021-01-11 12-32-52](https://user-images.githubusercontent.com/45695942/104230264-93bd6080-540a-11eb-8a8f-acc08225fa41.png)
Thanks! Happy New Year!

**Comment by xjli** [comment]
it is the apex version with pytorch compatibility issue, you can search this error online
See my post here for solution, https://github.com/microsoft/Oscar/issues/31

**Comment by Xuefei98** [comment]
So you mentioned cuda10.1 in the solution. I wonder if it also applies to cuda10.2?

**Comment by Xuefei98** [comment]
I just add git checkout f3a960f80244cf9e80558ab30f7f7e8cbf03c0a0 and then install apex. But it still returns the same error. Do we have to use cuda10.0 or 10.1 instead of cuda10.2?

**Comment by xjli** [comment]
I did not try cuda10.0 or cuda10.2. 
There are a lot of compatibility issues for cuda version, pytorch version, and apex version, you need to be careful to try here (find a good combination for these three).

**Comment by Xuefei98** [comment]
UPDATE:
You can use either PyTorch 1.4.0 or 1.5.0 along with CUDA10.2 and install apex successfully. But the same multi-gpu training error still exist. I googled it a little bit and it says it has something to do with PyTorch since it is taking people away from DataParallel. So my final solution is install pytorch1.2.0 and cuda10.0 using docker. Now everything works just fine.
