### ISSUE TITLE
about VinVL

### ISSUE THREAD

**Issue by JackWhite-rwx** [microsoft/Oscar#56]
Thanks once again for awesome work.I can't wait to learn about your new research VinVL.Thank you ver much.

**Comment by valuefish** [comment]
+1

**Comment by xhyandwyy** [comment]
+1

**Comment by yixuan-qiao** [comment]
+1

**Comment by xjli** [comment]
Thanks for all.
We plan to release the code next week (if all the processes go well).

**Comment by xjli** [comment]
Just released, thanks for all the patience.
