### ISSUE TITLE
HOW LONG did you train and fintune the image-captioning model?

### ISSUE THREAD

**Issue by XChuanLee** [microsoft/Oscar#6]
I have downloaded your coco_caption zip and tried to train and finetune the model, but it seems like costing a long time, don't know if I am correct. If convient, could I kown how long it cost when you train or finetune the model through your 8 V100?

**Comment by xjli** [comment]
On 4*V100 (32GB) machine, Base model, it is around 30+ hours for CE; another 30+ hours for CIDEr optimization; Large mode, it would more than 2 or 3 times of that time.

**Comment by xjli** [comment]
We released a trained captioning model in modelzoo readme, you can play with it. Thanks.
